<?php
//AUTHOR | MASTERCHO
@error_reporting(0);
@ini_set('output_buffering',0);
@ini_set('display_errors', 0);
@ini_set('log_errors',0);
fwrite(fopen("pagelist.txt","w"),"admin/
administrator/
admin1/
admin2/
admin3/
admin4/
admin5/
retel/
operator/
moderator/
adm/
_adm_/
timadmin/
teamadmin/
myadmin/
masuk/
4dm1n/
loggon/
adminpa/
admindisbun/
_admin_/
loginadm
login_admin/
_loginadmin_/
login_admin.php
_admin_/ 
_administrator_/
operator/
sika/
adminweb/
develop/
ketua/
redaktur/
author/
administrator/
adminweb/
user/
users/
dinkesadmin/
retel/
author/
panel/
paneladmin/
panellogin/
redaksi/
cp-admin/
Login@web/
admin1/
admin2/
admin3/
admin4/
admin5/
admin6/
admin7
admin8
admin9
admin10
master/
master/index.php
master/login.php
operator/index.php
sika/index.php
develop/index.php
ketua/index.php
redaktur/index.php
admin/index.php
administrator/index.php
adminweb/index.php
user/index.php
users/index.php
dinkesadmin/index.php
retel/index.php
author/index.php
panel/index.php
paneladmin/index.php
panellogin/index.php
redaksi/index.php
cp-admin/index.php
operator/login.php
sika/login.php
develop/login.php
ketua/login.php
redaktur/login.php
admin/login.php
administrator/login.php
adminweb/login.php
user/login.php
users/login.php
dinkesadmin/login.php
retel/login.php
author/login.php
panel/login.php
paneladmin/login.php
panellogin/login.php
redaksi/login.php
cp-admin/login.php
terasadmin/
terasadmin/index.php
terasadmin/login.php
rahasia/
rahasia/index.php
rahasia/admin.php
rahasia/login.php
dinkesadmin/
dinkesadmin/login.php
adminpmb/
adminpmb/index.php
adminpmb/login.php
system/
system/index.php
system/login.php
webadmin/
webadmin/index.php
webadmin/login.php
wpanel/
wpanel/index.php
wpanel/login.php
adminpanel/index.php
adminpanel/
adminpanel/login.php
adminkec/
adminkec/index.php
adminkec/login.php
admindesa/
admindesa/index.php
admindesa/login.php
adminkota/
adminkota/index.php
adminkota/login.php
admin123/
admin123/index.php
dologin/
home.asp/
supervise/amdin
relogin/adm
checkuser
relogin.php
relogin.asp
wp-admin
registration
suvervise
superman.php
member.php
home/admin
po-admin/
do_login.php
bo-login
bo_login.php/
index.php/admin
admiiin.php
masuk/adm
website_login/
dashboard/admin
dashboard.php
dashboard_adm
admin123/login.php
logout1/
logout/
pengelola/login
manageradm/
logout.asp
manager/adm
pengelola/web
auth/panel
logout/index.php
logout/login.php
controladm/
logout/admin.php
adminweb_setting/
CPanel
usuarios/
usuario/
administrator/
moderator/
webadmin/
adminarea/
bb-admin/
adminLogin/
admin_area/
panel-administracion/
instadmin/
memberadmin/
administratorlogin/
adm/
admin/account.php
admin/login.php
admin/admin.php
admin/account.php
admin_area/admin.php
admin_area/login.php
siteadmin/login.php
siteadmin/index.php
siteadmin/login.html
admin/account.html
admin/index.html
admin/login.html
admin/admin.html
admin_area/index.php
bb-admin/index.php
bb-admin/login.php
bb-admin/admin.php
admin/home.php
admin_area/login.html
admin_area/index.html
admin/controlpanel.php
admin.php
admincp/index.asp
admincp/login.asp
admincp/index.html
admin/account.html
adminpanel.html
webadmin.html
webadmin/index.html
webadmin/admin.html
webadmin/login.html
admin/admin_login.html
admin_login.html
panel-administracion/login.html
admin/cp.php
cp.php
administrator/index.php
administrator/login.php
nsw/admin/login.php
webadmin/login.php
admin/admin_login.php
admin_login.php
administrator/account.php
administrator.php
admin_area/admin.html
pages/admin/admin-login.php
admin/admin-login.php
admin-login.php
bb-admin/index.html
bb-admin/login.html
acceso.php
bb-admin/admin.html
admin/home.html
login.php
modelsearch/login.php
moderator.php
moderator/login.php
moderator/admin.php
account.php
pages/admin/admin-login.html
admin/admin-login.html
admin-login.html
controlpanel.php
admincontrol.php
admin/adminLogin.html
adminLogin.html
admin/adminLogin.html
home.html
rcjakar/admin/login.php
adminarea/index.html
adminarea/admin.html
webadmin.php
webadmin/index.php
webadmin/admin.php
admin/controlpanel.html
admin.html
admin/cp.html
cp.html
adminpanel.php
moderator.html
administrator/index.html
administrator/login.html
user.html
administrator/account.html
administrator.html
login.html
modelsearch/login.html
moderator/login.html
adminarea/login.html
panel-administracion/index.html
panel-administracion/admin.html
modelsearch/index.html
modelsearch/admin.html
admincontrol/login.html
adm/index.html
adm.html
moderator/admin.html
user.php
account.html
controlpanel.html
admincontrol.html
panel-administracion/login.php
wp-login.php
adminLogin.php
admin/adminLogin.php
home.php
admin.php
adminarea/index.php
adminarea/admin.php
adminarea/login.php
panel-administracion/index.php
panel-administracion/admin.php
modelsearch/index.php
modelsearch/admin.php
admincontrol/login.php
adm/admloginuser.php
admloginuser.php
admin2.php
admin2/login.php
admin2/index.php
usuarios/login.php
adm/index.php
adm.php
affiliate.php
adm_auth.php
memberadmin.php
administratorlogin.php");
print "\e[34m           _    __  _____  __  __    ___         ___ 
  /\/\    /_\  / _\/__   \/__\/__\  / __\ /\  /\/___\
 /    \  //_\\ \ \   / /\/_\ / \// / /   / /_/ //  //
/ /\/\ \/  _  \_\ \ / / //__/ _  \/ /___/ __  / \_// 
\/    \/\_/ \_/\__/ \/  \__/\/ \_/\____/\/ /_/\___/  
";
echo "\e[93m\n#######PAGE FINDER BY MASTERCHO######\n";
echo "\nInput URL : "; $target=trim(fgets(STDIN));
$page=explode("\n", file_get_contents('pagelist.txt'));
foreach($page as $lol) {
$cyberserkers=$target."/".$lol;
$ch=curl_init($cyberserkers);
curl_setopt($ch, CURLOPT_NOBODY, true);
curl_exec($ch);
$azzatssins=curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);
if($azzatssins==200){
echo "\e[92m \n>> ". $cyberserkers." [Check it > Status 200 OK]";
}elseif($azzatssins==302){
echo "\e[92m \n>> ". $cyberserkers." [Check it > Status 302 Found]";
}else{
echo "\e[91m \n". $cyberserkers." ( ".$azzatssins." )\n";
}}